### ISSUE TITLE
Add scratchblocks export option

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/sb-edit#11]
@towerofnix made a thing: https://git.ed1.club/florrie/scratchblocks-generator-3.git/

I haven't looked into it much because I'm lazy, but it's on my list. I would be thrilled if somebody (that means *you*) took this and turned it into a PR with scratchblocks support.

**Comment by towerofnix** [comment]
I'm definitely up for figuring this out soon™! After obsolete blocks that is.

I'm not 100% decided on what the output format should be, exactly: scratchblocks doesn't inherently have a way to describe multiple sprites. I could pretty easily just do `// Sprite1` (etc) in the output; or I could output an object, similar to the toScratchJS output but with just the target names instead of filenames (since files don't mean anything to scratchblocks). I'm leaning more toward the latter, since it'd be more useful for writing [tools](https://florrie.ed1.club/sb3-gen/) around the API.

**Comment by PullJosh** [comment]
I've been thinking about the scratch-js output format as well. I'm not thrilled about it.

For both scratch-js and scratchblocks, it seems like it could be valuable to allow translating individual project assets (instances of `Sprite`, `Stage`, `Script`, etc...) one at a time. Not sure what the best API for this is.
