### ISSUE TITLE
Can't open projects with empty boolean custom-proc inputs

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/sb-edit#2]
I created a simple project which has a custom procedure definition containing a boolean and a caller block which does not have anything in that boolean block. The result is an error:

```
TypeError: Cannot read property 'value' of undefined
    at /home/florrie/Documents/scratchblocks-generator-3/sb-edit/lib/io/sb3/fromSb3.js:282:46
    at Array.map (<anonymous>)
    at translateInputs (/home/florrie/Documents/scratchblocks-generator-3/sb-edit/lib/io/sb3/fromSb3.js:280:71)
    at getBlockInputs (/home/florrie/Documents/scratchblocks-generator-3/sb-edit/lib/io/sb3/fromSb3.js:131:38)
    at blockWithNext (/home/florrie/Documents/scratchblocks-generator-3/sb-edit/lib/io/sb3/fromSb3.js:360:21)
    at /home/florrie/Documents/scratchblocks-generator-3/sb-edit/lib/io/sb3/fromSb3.js:505:98
    at Array.map (<anonymous>)
    at /home/florrie/Documents/scratchblocks-generator-3/sb-edit/lib/io/sb3/fromSb3.js:502:54
    at step (/home/florrie/Documents/scratchblocks-generator-3/sb-edit/lib/io/sb3/fromSb3.js:44:23)
    at Object.next (/home/florrie/Documents/scratchblocks-generator-3/sb-edit/lib/io/sb3/fromSb3.js:25:53)
```

To narrow the issue, I tried two things:

1. I called a custom block with only a text/number input, and didn't put anything in that input. This project loaded fine (the value was just an empty string).
2. I used a "wait until" block with no block inside the input. This project also loaded fine (the block's inputs list just contained an `undefined`).

So it follows this issue is only for empty boolean inputs in callers of custom blocks.

The project: [empty-custom-boolean.zip](https://github.com/PullJosh/sb-edit/files/3969956/empty-custom-boolean.zip) (rename to .sb3 - github doesn't accept .sb3 uploads as-is.)

**Comment by PullJosh** [comment]
Oh wow! Good catch. The Scratch 3.0 format is super weird. If you place a block in the input and then remove it again, sb-edit will do fine because the .sb3 file will contain a sort of "null" value for the boolean input. However, if you never put anything inside the input in the first place, the input *isn't even defined* in the .sb3 file. Super weird.

**Comment by PullJosh** [comment]
Fixed in f4608cf2e4cf36e9849ed11664d5743b83fa8220 (hopefully). Solution isn't perfect but it's a decent patch job.

**Comment by towerofnix** [comment]
Thanks! I think you can get the missing type by finding the matching-index non-label input on the procedure definition. So, in my custom block it's the second input (i = 1 on the caller); on the definition it'll be i=2, because there's one label before it.

**Comment by PullJosh** [comment]
@towerofnix Makes sense in principle, although -- unless I've missed something obvious -- the current code actually makes that relatively difficult to do in practice. (It's tricky to access the procedure definition from within the code that handles calls to that procedure.)

Currently the `Project` class (and related classes like `Script`, etc...) pretty much just takes a carbon copy of the information contained in the sb3, which means that relationships between project parts are usually represented with string ids. It would be good to replace those string ids with actual references to the instances they represent. (So, for example, the input value of the "set costume" block would be stored as a reference to the costume object rather than a string with the costume name. That kind of thing.) This would make accessing the procedure definition (and thus the input types) easier.
