### ISSUE TITLE
Leopard: Non-warp-mode procedures called from warp-mode procedures do not execute in warp mode

### ISSUE THREAD

**Issue by adroitwhiz** [PullJosh/sb-edit#55]
This seems to be a limitation both in Leopard's design and in sb-edit, so I'm not sure which repo this should go in.

In Scratch, if a procedure is marked "run without screen refresh", all procedures called from within that procedure will run without refreshing the screen, even if those child procedures are not themselves marked "run without screen refresh".

In Leopard, those child procedures will always refresh the screen (yield).

A demonstration of this can be seen at https://scratch.mit.edu/projects/470160866/editor/.

**Comment by PullJosh** [comment]
Aha! This is a great observation. I never fully understood what the issue was with warping in Leopard.

I don't have a super elegant solution, but one possibility is to create a `warp` function that wraps a generator and turns it into an instant script:
```js
function* mySlowProcedure(a, b) {
	for (let i = a; i <= b; i++) {
  	console.log(i);
  }
}

function warp(procedure) {
	return (...args) => {
  	const inst = procedure(...args);
    let done = false;
    while (!done) {
    	done = inst.next().done;
    }
  }
}

// Inside a "run without screen refresh" procedure, call slow procedures like this:
warp(mySlowProcedure)(1, 10);
```

Then sb-edit could add `warp` where it's needed (when calling a procedure from within a "no screen refresh" block). This doesn't feel elegant or intuitive, but it's the best idea I could come up with in 10 minutes.

**Comment by adroitwhiz** [comment]
Abstracting this into a `warp` function is much cleaner than my idea. That sounds like a good solution to me!

**Comment by PullJosh** [comment]
This is all fixed now and the website is updated! Thank you @adroitwhiz!
